version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
